//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitLogProjectLocation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid DefaultExteriorConfiguration {
            get {
                return ((global::System.Guid)(this["DefaultExteriorConfiguration"]));
            }
            set {
                this["DefaultExteriorConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0001")]
        public double Tolerance {
            get {
                return ((double)(this["Tolerance"]));
            }
            set {
                this["Tolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int RoundCount {
            get {
                return ((int)(this["RoundCount"]));
            }
            set {
                this["RoundCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MinWallWidth {
            get {
                return ((int)(this["MinWallWidth"]));
            }
            set {
                this["MinWallWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int ProjectionDepth {
            get {
                return ((int)(this["ProjectionDepth"]));
            }
            set {
                this["ProjectionDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ExteriorFaceMinWidthBetween {
            get {
                return ((int)(this["ExteriorFaceMinWidthBetween"]));
            }
            set {
                this["ExteriorFaceMinWidthBetween"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExteriorMinWidthFaceRemove {
            get {
                return ((int)(this["ExteriorMinWidthFaceRemove"]));
            }
            set {
                this["ExteriorMinWidthFaceRemove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseWindow {
            get {
                return ((bool)(this["CloseWindow"]));
            }
            set {
                this["CloseWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DimensionDilutionWorkVariant {
            get {
                return ((int)(this["DimensionDilutionWorkVariant"]));
            }
            set {
                this["DimensionDilutionWorkVariant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid DefaultByLineConfiguration {
            get {
                return ((global::System.Guid)(this["DefaultByLineConfiguration"]));
            }
            set {
                this["DefaultByLineConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid DefaultInteriorConfiguration {
            get {
                return ((global::System.Guid)(this["DefaultInteriorConfiguration"]));
            }
            set {
                this["DefaultInteriorConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int OffsetFromWallForInteriorDimensions {
            get {
                return ((int)(this["OffsetFromWallForInteriorDimensions"]));
            }
            set {
                this["OffsetFromWallForInteriorDimensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WallWidth_DimWalls {
            get {
                return ((bool)(this["WallWidth_DimWalls"]));
            }
            set {
                this["WallWidth_DimWalls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WallWidth_DimColumns {
            get {
                return ((bool)(this["WallWidth_DimColumns"]));
            }
            set {
                this["WallWidth_DimColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public int WallWidth_PylonMaxLenght {
            get {
                return ((int)(this["WallWidth_PylonMaxLenght"]));
            }
            set {
                this["WallWidth_PylonMaxLenght"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WallWidth_FilterByCutZ {
            get {
                return ((bool)(this["WallWidth_FilterByCutZ"]));
            }
            set {
                this["WallWidth_FilterByCutZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WallFaceToGridDimensions {
            get {
                return ((bool)(this["WallFaceToGridDimensions"]));
            }
            set {
                this["WallFaceToGridDimensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int InteriorOffset {
            get {
                return ((int)(this["InteriorOffset"]));
            }
            set {
                this["InteriorOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InteriorDimGrids {
            get {
                return ((bool)(this["InteriorDimGrids"]));
            }
            set {
                this["InteriorDimGrids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InteriorDimOpenings {
            get {
                return ((bool)(this["InteriorDimOpenings"]));
            }
            set {
                this["InteriorDimOpenings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InteriorExclusionByTypeName {
            get {
                return ((string)(this["InteriorExclusionByTypeName"]));
            }
            set {
                this["InteriorExclusionByTypeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InteriorExclusionByMaterialName {
            get {
                return ((string)(this["InteriorExclusionByMaterialName"]));
            }
            set {
                this["InteriorExclusionByMaterialName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int WallWidth_MinWallLenght {
            get {
                return ((int)(this["WallWidth_MinWallLenght"]));
            }
            set {
                this["WallWidth_MinWallLenght"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WallWidth_DimOpenings {
            get {
                return ((bool)(this["WallWidth_DimOpenings"]));
            }
            set {
                this["WallWidth_DimOpenings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WallWidth_DimOpeningsToGrids {
            get {
                return ((bool)(this["WallWidth_DimOpeningsToGrids"]));
            }
            set {
                this["WallWidth_DimOpeningsToGrids"] = value;
            }
        }
    }
}
